#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from helpers import get_user_timeline
from analyzer import Analyzer
from termcolor import colored

def main():
    
    # ensure proper usage
    if not len(sys.argv) == 2 or not sys.argv[1].startswith("@") or len(sys.argv[1]) == 1:
        print("Usage: ./tweets @username")
        
    screen_name = sys.argv[1].lstrip("@")
    tweets = get_user_timeline(screen_name, 50)
    #print(tweets)
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")    
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score,tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score,tweet), "red"))
        else:
            print(colored("{} {}".format(score,tweet), "yellow"))
    
if __name__ == "__main__":
    main()