#!/usr/bin/env python3

# smile.py
# Programmeren 02 - pset 06 - exercise 04
# By Maxim Stomphorst
# 
# Determining if a word has a positive,negative or neutral intention.
# positive prints green smiley :)
# negative prints red smiley   :(
# neutral prints yellow smiley :|

import os
import sys

from analyzer import Analyzer
from termcolor import colored


def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile word")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # analyze word
    score = analyzer.analyze(sys.argv[1])

    # print according smile and color
    if score > 0.0:
        print(colored(":)", "green"))
    elif score < 0.0:
        print(colored(":(", "red"))
    else:
        print(colored(":|", "yellow"))


if __name__ == "__main__":
    main()

